# This Makefile builds the code for the daughterboard used in the Raspberry Pi based matrix.
# This has a slightly different pinout from the Etherten version, which is selected with the
# 

ARDUINO_DIR = /usr/share/arduino
TARGET = arduino_matrix_driver
ARDUINO_LIBS = SPI
BOARD_TAG = pro328
include Arduino.mk
